version: "3.9"
services:
        roscore:
                build: ./roscore
                hostname: 'convert_docker_roscore_master'
                container_name: 'convert_docker_roscore_master'
                volumes:
                        - storage:/storage
        lidar-sdk-node:
                build: ./lidar_sdk_node
                hostname: 'convert_docker_lidar_sdk_node'
                container_name: 'convert_docker_lidar_sdk_node'
                ports:
                        - "192.168.0.2:6699:6699/udp"
                        - "192.168.0.2:7788:7788/udp"
volumes:
        storage:
                external: true