version: "3.9"
services:
    rosbag_decode_roscore:
        build: ./rosbag_decode_roscore
        hostname: "docker_rosbag_decode_roscore_master"
        container_name: "docker_rosbag_decode_roscore_master"
        volumes:
            - output:/output
            - sharedstorage:/storage

volumes:
    output:
        external: true
    sharedstorage:
        external: true
